### ISSUE TITLE
secured vs production clusers in the devsecops pattern

### ISSUE THREAD

**Issue by steven-ellis** [hybrid-cloud-patterns/docs#168]
The documentation requests that the  production environment be tagged
`clusterGroup=secured`

But the **values-hub.yaml**  from https://github.com/hybrid-cloud-patterns/multicluster-devsecops assumes the label
`clusterGroup=prod`

If we don't apply the correct label then services aren't deployed to production

**Comment by ipbabble** [comment]
@steven-ellis  can you look over this? https://github.com/hybrid-cloud-patterns/docs/pull/169
