### ISSUE TITLE
variables missing from doc

### ISSUE THREAD

**Issue by ikke-t** [hybrid-cloud-patterns/docs#68]
Hi,

While I was reading the docs I noticed there is error in docs layout. Some helm variables are not visible, the brackets need to be escaped in the source.

At leat this doc is having the problem:

https://github.com/hybrid-cloud-patterns/docs/blob/gh-pages/building-vps/structure.md

The {{ needs to be escaped.

**Comment by ikke-t** [comment]
The fix is to use raw: {% raw %}{{ variables }}{% endraw %}

**Comment by mbaldessari** [comment]
Thanks @ikke-t !
